// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HamzaDocumentDataSlicesSlice = FeatureArticleSlice;

/**
 * Content for LandingPage documents
 */
interface HamzaDocumentData {
  /**
   * Slice Zone field in *LandingPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: hamza.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HamzaDocumentDataSlicesSlice>; /**
   * Meta Title field in *LandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: hamza.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *LandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: hamza.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *LandingPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hamza.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * LandingPage document from Prismic
 *
 * - **API ID**: `hamza`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HamzaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HamzaDocumentData>, "hamza", Lang>;

type MainnavigationDocumentDataSlicesSlice = MainNavigationSlice;

/**
 * Content for MainNavigation documents
 */
interface MainnavigationDocumentData {
  /**
   * Slice Zone field in *MainNavigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mainnavigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<MainnavigationDocumentDataSlicesSlice>; /**
   * Meta Title field in *MainNavigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: mainnavigation.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *MainNavigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: mainnavigation.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *MainNavigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mainnavigation.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * MainNavigation document from Prismic
 *
 * - **API ID**: `mainnavigation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainnavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MainnavigationDocumentData>,
    "mainnavigation",
    Lang
  >;

type NavbarDocumentDataSlicesSlice = AnnouncementBarSlice;

/**
 * Content for navbar documents
 */
interface NavbarDocumentData {
  /**
   * Slice Zone field in *navbar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NavbarDocumentDataSlicesSlice>; /**
   * Meta Title field in *navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: navbar.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *navbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: navbar.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *navbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * navbar document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NavbarDocumentData>, "navbar", Lang>;

type NewscontentcardDocumentDataSlicesSlice = FeaturedContentCardsSlice;

/**
 * Content for NewsContentCard documents
 */
interface NewscontentcardDocumentData {
  /**
   * Slice Zone field in *NewsContentCard*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: newscontentcard.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NewscontentcardDocumentDataSlicesSlice>; /**
   * Meta Title field in *NewsContentCard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: newscontentcard.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *NewsContentCard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: newscontentcard.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *NewsContentCard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: newscontentcard.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * NewsContentCard document from Prismic
 *
 * - **API ID**: `newscontentcard`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewscontentcardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NewscontentcardDocumentData>,
    "newscontentcard",
    Lang
  >;

type SearchbarDocumentDataSlicesSlice = SearchBarSlice;

/**
 * Content for Searchbar documents
 */
interface SearchbarDocumentData {
  /**
   * Slice Zone field in *Searchbar*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: searchbar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SearchbarDocumentDataSlicesSlice>; /**
   * Meta Title field in *Searchbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: searchbar.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Searchbar*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: searchbar.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Searchbar*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: searchbar.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Searchbar document from Prismic
 *
 * - **API ID**: `searchbar`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SearchbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SearchbarDocumentData>,
    "searchbar",
    Lang
  >;

type SimplefooterDocumentDataSlicesSlice = SimpleFooterSlice;

/**
 * Content for SimpleFooter documents
 */
interface SimplefooterDocumentData {
  /**
   * Slice Zone field in *SimpleFooter*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: simplefooter.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SimplefooterDocumentDataSlicesSlice>; /**
   * Meta Title field in *SimpleFooter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: simplefooter.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *SimpleFooter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: simplefooter.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *SimpleFooter*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: simplefooter.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * SimpleFooter document from Prismic
 *
 * - **API ID**: `simplefooter`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SimplefooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SimplefooterDocumentData>,
    "simplefooter",
    Lang
  >;

type TopnewsDocumentDataSlicesSlice = HighlightedContentCarouselSlice;

/**
 * Content for topnews documents
 */
interface TopnewsDocumentData {
  /**
   * Slice Zone field in *topnews*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: topnews.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TopnewsDocumentDataSlicesSlice>; /**
   * Meta Title field in *topnews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: topnews.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *topnews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: topnews.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *topnews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: topnews.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * topnews document from Prismic
 *
 * - **API ID**: `topnews`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TopnewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TopnewsDocumentData>,
    "topnews",
    Lang
  >;

export type AllDocumentTypes =
  | HamzaDocument
  | MainnavigationDocument
  | NavbarDocument
  | NewscontentcardDocument
  | SearchbarDocument
  | SimplefooterDocument
  | TopnewsDocument;

/**
 * Primary content in *AnnouncementBar → Default → Primary*
 */
export interface AnnouncementBarSliceDefaultPrimary {
  /**
   * Label field in *AnnouncementBar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Message field in *AnnouncementBar → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.default.primary.message
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  message: prismic.RichTextField;

  /**
   * Background Color field in *AnnouncementBar → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;
}

/**
 * Default variation for AnnouncementBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Basic announcement bar with a label and message text.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AnnouncementBarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AnnouncementBarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AnnouncementBar*
 */
type AnnouncementBarSliceVariation = AnnouncementBarSliceDefault;

/**
 * AnnouncementBar Shared Slice
 *
 * - **API ID**: `announcement_bar`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AnnouncementBarSlice = prismic.SharedSlice<
  "announcement_bar",
  AnnouncementBarSliceVariation
>;

/**
 * Primary content in *FeatureArticle → Image Left, Text Right → Primary*
 */
export interface FeatureArticleSliceImageLeftTextRightPrimary {
  /**
   * Main Image field in *FeatureArticle → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_article.image_left_text_right.primary.main_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Tag/Category field in *FeatureArticle → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_article.image_left_text_right.primary.tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag: prismic.KeyTextField;

  /**
   * Title field in *FeatureArticle → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_article.image_left_text_right.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Summary field in *FeatureArticle → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_article.image_left_text_right.primary.summary
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary: prismic.RichTextField;

  /**
   * Post Time field in *FeatureArticle → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_article.image_left_text_right.primary.post_time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  post_time: prismic.KeyTextField;

  /**
   * Author Name field in *FeatureArticle → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_article.image_left_text_right.primary.author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Read Time field in *FeatureArticle → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_article.image_left_text_right.primary.read_time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  read_time: prismic.KeyTextField;

  /**
   * Show Action Icons field in *FeatureArticle → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_article.image_left_text_right.primary.show_icons
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_icons: prismic.BooleanField;
}

/**
 * Image Left, Text Right variation for FeatureArticle Slice
 *
 * - **API ID**: `image_left_text_right`
 * - **Description**: An article highlight section with image on the left and text (headline, summary, meta info) on the right.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureArticleSliceImageLeftTextRight =
  prismic.SharedSliceVariation<
    "image_left_text_right",
    Simplify<FeatureArticleSliceImageLeftTextRightPrimary>,
    never
  >;

/**
 * Slice variation for *FeatureArticle*
 */
type FeatureArticleSliceVariation = FeatureArticleSliceImageLeftTextRight;

/**
 * FeatureArticle Shared Slice
 *
 * - **API ID**: `feature_article`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureArticleSlice = prismic.SharedSlice<
  "feature_article",
  FeatureArticleSliceVariation
>;

/**
 * Item in *FeaturedContentCards → Horizontal List → Primary → Cards*
 */
export interface FeaturedContentCardsSliceDefaultHorizontalListPrimaryCardsItem {
  /**
   * Thumbnail Image field in *FeaturedContentCards → Horizontal List → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_content_cards.default_horizontal_list.primary.cards[].thumbnail_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail_image: prismic.ImageField<never>;

  /**
   * Title field in *FeaturedContentCards → Horizontal List → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_content_cards.default_horizontal_list.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *FeaturedContentCards → Horizontal List → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_content_cards.default_horizontal_list.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Timestamp field in *FeaturedContentCards → Horizontal List → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_content_cards.default_horizontal_list.primary.cards[].timestamp
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  timestamp: prismic.KeyTextField;

  /**
   * Author field in *FeaturedContentCards → Horizontal List → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_content_cards.default_horizontal_list.primary.cards[].author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Read Time field in *FeaturedContentCards → Horizontal List → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_content_cards.default_horizontal_list.primary.cards[].read_time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  read_time: prismic.KeyTextField;

  /**
   * Likes Count field in *FeaturedContentCards → Horizontal List → Primary → Cards*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_content_cards.default_horizontal_list.primary.cards[].likes_count
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  likes_count: prismic.NumberField;

  /**
   * Comments Count field in *FeaturedContentCards → Horizontal List → Primary → Cards*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_content_cards.default_horizontal_list.primary.cards[].comments_count
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  comments_count: prismic.NumberField;

  /**
   * Liked by User field in *FeaturedContentCards → Horizontal List → Primary → Cards*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_content_cards.default_horizontal_list.primary.cards[].liked
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  liked: prismic.BooleanField;
}

/**
 * Primary content in *FeaturedContentCards → Horizontal List → Primary*
 */
export interface FeaturedContentCardsSliceDefaultHorizontalListPrimary {
  /**
   * Cards field in *FeaturedContentCards → Horizontal List → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_content_cards.default_horizontal_list.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<FeaturedContentCardsSliceDefaultHorizontalListPrimaryCardsItem>
  >;
}

/**
 * Horizontal List variation for FeaturedContentCards Slice
 *
 * - **API ID**: `default_horizontal_list`
 * - **Description**: Displays multiple content cards in a horizontal (side-by-side) layout. Each card contains structured information about an article or content piece.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedContentCardsSliceDefaultHorizontalList =
  prismic.SharedSliceVariation<
    "default_horizontal_list",
    Simplify<FeaturedContentCardsSliceDefaultHorizontalListPrimary>,
    never
  >;

/**
 * Slice variation for *FeaturedContentCards*
 */
type FeaturedContentCardsSliceVariation =
  FeaturedContentCardsSliceDefaultHorizontalList;

/**
 * FeaturedContentCards Shared Slice
 *
 * - **API ID**: `featured_content_cards`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedContentCardsSlice = prismic.SharedSlice<
  "featured_content_cards",
  FeaturedContentCardsSliceVariation
>;

/**
 * Item in *HighlightedContentCarousel → Default → Primary → Items*
 */
export interface HighlightedContentCarouselSliceDefaultPrimaryItemsItem {
  /**
   * Media field in *HighlightedContentCarousel → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_content_carousel.default.primary.items[].media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  media: prismic.ImageField<never>;

  /**
   * Category Label field in *HighlightedContentCarousel → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_content_carousel.default.primary.items[].category_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category_label: prismic.KeyTextField;

  /**
   * Title field in *HighlightedContentCarousel → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_content_carousel.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *HighlightedContentCarousel → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_content_carousel.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Item Link field in *HighlightedContentCarousel → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_content_carousel.default.primary.items[].item_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  item_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Is Featured field in *HighlightedContentCarousel → Default → Primary → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_content_carousel.default.primary.items[].is_featured
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_featured: prismic.BooleanField;
}

/**
 * Primary content in *HighlightedContentCarousel → Default → Primary*
 */
export interface HighlightedContentCarouselSliceDefaultPrimary {
  /**
   * Section Title field in *HighlightedContentCarousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_content_carousel.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Items field in *HighlightedContentCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: highlighted_content_carousel.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<HighlightedContentCarouselSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for HighlightedContentCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Basic horizontally scrollable carousel of featured content items, each containing an image, label, title, description, and optional metadata.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HighlightedContentCarouselSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<HighlightedContentCarouselSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *HighlightedContentCarousel*
 */
type HighlightedContentCarouselSliceVariation =
  HighlightedContentCarouselSliceDefault;

/**
 * HighlightedContentCarousel Shared Slice
 *
 * - **API ID**: `highlighted_content_carousel`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HighlightedContentCarouselSlice = prismic.SharedSlice<
  "highlighted_content_carousel",
  HighlightedContentCarouselSliceVariation
>;

/**
 * Item in *MainNavigation → Default → Primary → Navigation Links*
 */
export interface MainNavigationSliceDefaultPrimaryNavLinksItem {
  /**
   * Label field in *MainNavigation → Default → Primary → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.default.primary.nav_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *MainNavigation → Default → Primary → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.default.primary.nav_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *MainNavigation → Default → Primary*
 */
export interface MainNavigationSliceDefaultPrimary {
  /**
   * Logo field in *MainNavigation → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation Links field in *MainNavigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.default.primary.nav_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  nav_links: prismic.GroupField<
    Simplify<MainNavigationSliceDefaultPrimaryNavLinksItem>
  >;

  /**
   * Profile Link field in *MainNavigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.default.primary.profile_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  profile_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Search Link field in *MainNavigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.default.primary.search_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  search_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Menu Link field in *MainNavigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.default.primary.menu_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  menu_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for MainNavigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard horizontal navigation bar with logo, nav links, and utility icons.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MainNavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainNavigationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MainNavigation*
 */
type MainNavigationSliceVariation = MainNavigationSliceDefault;

/**
 * MainNavigation Shared Slice
 *
 * - **API ID**: `main_navigation`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MainNavigationSlice = prismic.SharedSlice<
  "main_navigation",
  MainNavigationSliceVariation
>;

/**
 * Primary content in *SearchBar → Default → Primary*
 */
export interface SearchBarSliceDefaultPrimary {
  /**
   * Title field in *SearchBar → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: search_bar.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Input Placeholder field in *SearchBar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: search_bar.default.primary.input_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  input_placeholder: prismic.KeyTextField;
}

/**
 * Default variation for SearchBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default layout with a heading and a search input field with placeholder text.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SearchBarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SearchBarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SearchBar*
 */
type SearchBarSliceVariation = SearchBarSliceDefault;

/**
 * SearchBar Shared Slice
 *
 * - **API ID**: `search_bar`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SearchBarSlice = prismic.SharedSlice<
  "search_bar",
  SearchBarSliceVariation
>;

/**
 * Item in *SimpleFooter → Default → Primary → Legal Links*
 */
export interface SimpleFooterSliceDefaultPrimaryLegalLinksItem {
  /**
   * Legal Link field in *SimpleFooter → Default → Primary → Legal Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_footer.default.primary.legal_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *SimpleFooter → Default → Primary → Navigation Links*
 */
export interface SimpleFooterSliceDefaultPrimaryNavigationLinksItem {
  /**
   * Navigation Link field in *SimpleFooter → Default → Primary → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_footer.default.primary.navigation_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *SimpleFooter → Default → Primary → Social Links*
 */
export interface SimpleFooterSliceDefaultPrimarySocialLinksItem {
  /**
   * Icon Link field in *SimpleFooter → Default → Primary → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_footer.default.primary.social_links[].icon_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  icon_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *SimpleFooter → Default → Primary*
 */
export interface SimpleFooterSliceDefaultPrimary {
  /**
   * Logo field in *SimpleFooter → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_footer.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Copyright Text field in *SimpleFooter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: copyright 2020 | NBC NEWS
   * - **API ID Path**: simple_footer.default.primary.copyright_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_text: prismic.KeyTextField;

  /**
   * Legal Links field in *SimpleFooter → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_footer.default.primary.legal_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  legal_links: prismic.GroupField<
    Simplify<SimpleFooterSliceDefaultPrimaryLegalLinksItem>
  >;

  /**
   * Navigation Links field in *SimpleFooter → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_footer.default.primary.navigation_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation_links: prismic.GroupField<
    Simplify<SimpleFooterSliceDefaultPrimaryNavigationLinksItem>
  >;

  /**
   * Social Links field in *SimpleFooter → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_footer.default.primary.social_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<
    Simplify<SimpleFooterSliceDefaultPrimarySocialLinksItem>
  >;
}

/**
 * Default variation for SimpleFooter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard footer with logo, copyright, multiple link groups, and icons.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SimpleFooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SimpleFooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SimpleFooter*
 */
type SimpleFooterSliceVariation = SimpleFooterSliceDefault;

/**
 * SimpleFooter Shared Slice
 *
 * - **API ID**: `simple_footer`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SimpleFooterSlice = prismic.SharedSlice<
  "simple_footer",
  SimpleFooterSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HamzaDocument,
      HamzaDocumentData,
      HamzaDocumentDataSlicesSlice,
      MainnavigationDocument,
      MainnavigationDocumentData,
      MainnavigationDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataSlicesSlice,
      NewscontentcardDocument,
      NewscontentcardDocumentData,
      NewscontentcardDocumentDataSlicesSlice,
      SearchbarDocument,
      SearchbarDocumentData,
      SearchbarDocumentDataSlicesSlice,
      SimplefooterDocument,
      SimplefooterDocumentData,
      SimplefooterDocumentDataSlicesSlice,
      TopnewsDocument,
      TopnewsDocumentData,
      TopnewsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AnnouncementBarSlice,
      AnnouncementBarSliceDefaultPrimary,
      AnnouncementBarSliceVariation,
      AnnouncementBarSliceDefault,
      FeatureArticleSlice,
      FeatureArticleSliceImageLeftTextRightPrimary,
      FeatureArticleSliceVariation,
      FeatureArticleSliceImageLeftTextRight,
      FeaturedContentCardsSlice,
      FeaturedContentCardsSliceDefaultHorizontalListPrimaryCardsItem,
      FeaturedContentCardsSliceDefaultHorizontalListPrimary,
      FeaturedContentCardsSliceVariation,
      FeaturedContentCardsSliceDefaultHorizontalList,
      HighlightedContentCarouselSlice,
      HighlightedContentCarouselSliceDefaultPrimaryItemsItem,
      HighlightedContentCarouselSliceDefaultPrimary,
      HighlightedContentCarouselSliceVariation,
      HighlightedContentCarouselSliceDefault,
      MainNavigationSlice,
      MainNavigationSliceDefaultPrimaryNavLinksItem,
      MainNavigationSliceDefaultPrimary,
      MainNavigationSliceVariation,
      MainNavigationSliceDefault,
      SearchBarSlice,
      SearchBarSliceDefaultPrimary,
      SearchBarSliceVariation,
      SearchBarSliceDefault,
      SimpleFooterSlice,
      SimpleFooterSliceDefaultPrimaryLegalLinksItem,
      SimpleFooterSliceDefaultPrimaryNavigationLinksItem,
      SimpleFooterSliceDefaultPrimarySocialLinksItem,
      SimpleFooterSliceDefaultPrimary,
      SimpleFooterSliceVariation,
      SimpleFooterSliceDefault,
    };
  }
}
