// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  announcement_bar: dynamic(() => import("./AnnouncementBar")),
  feature_article: dynamic(() => import("./FeatureArticle")),
  featured_content_cards: dynamic(() => import("./FeaturedContentCards")),
  highlighted_content_carousel: dynamic(
    () => import("./HighlightedContentCarousel"),
  ),
  main_navigation: dynamic(() => import("./MainNavigation")),
  search_bar: dynamic(() => import("./SearchBar")),
  simple_footer: dynamic(() => import("./SimpleFooter")),
};
